const data = {
  page: 1,
  results: [
    {
      backdrop_path: "/sjxtIUCWR74yPPcZFfTsToepfWm.jpg",
      first_air_date: "2021-05-04",
      genre_ids: [10765, 10759, 16],
      id: 105971,
      name: "Star Wars: The Bad Batch",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Star Wars: The Bad Batch",
      overview:
        "Follow the elite and experimental Clones of the Bad Batch as they find their way in a rapidly changing galaxy in the aftermath of the Clone Wars.",
      poster_path: "/WjQmEWFrOf98nT5aEfUfVYz9N2.jpg",
      vote_average: 9.5,
      vote_count: 28,
      popularity: 86.779,
      media_type: "tv",
    },
    {
      title: "Tom Clancy's Without Remorse",
      adult: false,
      backdrop_path: "/fPGeS6jgdLovQAKunNHX8l0avCy.jpg",
      id: 567189,
      original_language: "en",
      original_title: "Tom Clancy's Without Remorse",
      poster_path: "/rEm96ib0sPiZBADNKBHKBv5bve9.jpg",
      video: false,
      vote_average: 7.2,
      vote_count: 452,
      overview:
        "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.",
      release_date: "2021-04-29",
      genre_ids: [28, 12, 53, 10752],
      popularity: 847.823,
      media_type: "movie",
    },
    {
      original_language: "en",
      original_title: "The Mitchells vs. The Machines",
      poster_path: "/1RjkFdP1pQrqQ3DYKuxR9JnQ5JO.jpg",
      video: false,
      vote_average: 8.1,
      id: 501929,
      release_date: "2021-04-22",
      vote_count: 220,
      title: "The Mitchells vs. The Machines",
      adult: false,
      backdrop_path: "/5g0gisu56NsCGiMa00HWINbc25X.jpg",
      overview:
        "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
      genre_ids: [16, 12, 35, 10751, 878, 28],
      popularity: 169.011,
      media_type: "movie",
    },
    {
      original_title: "Mortal Kombat",
      poster_path: "/xGuOF1T3WmPsAcQEQJfnG7Ud9f8.jpg",
      video: false,
      vote_average: 7.8,
      overview:
        "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
      release_date: "2021-04-07",
      id: 460465,
      adult: false,
      backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
      vote_count: 2042,
      genre_ids: [14, 28, 12, 878, 53],
      title: "Mortal Kombat",
      original_language: "en",
      popularity: 5088.686,
      media_type: "movie",
    },
    {
      overview:
        "Catherine Clare reluctantly trades life in 1980 Manhattan for a remote home in the tiny hamlet of Chosen, New York, after her husband George lands a job teaching art history at a small Hudson Valley college. Even as she does her best to transform the old dairy farm into a place where young daughter Franny will be happy, Catherine increasingly finds herself isolated and alone. She soon comes to sense a sinister darkness lurking both in the walls of the ramshackle property—and in her marriage to George.",
      release_date: "2021-04-29",
      adult: false,
      backdrop_path: "/owOBJlzH3j3YHUbr3XqSH10CWzo.jpg",
      vote_count: 188,
      genre_ids: [27, 9648, 18, 53],
      original_title: "Things Heard \u0026 Seen",
      original_language: "en",
      id: 631060,
      poster_path: "/9tSkNmGt1K5Lgf0L0BTHHYJNz0W.jpg",
      title: "Things Heard \u0026 Seen",
      video: false,
      vote_average: 5.9,
      popularity: 147.393,
      media_type: "movie",
    },
    {
      video: false,
      vote_average: 6.3,
      overview:
        "With the future of the human race at stake, a group of young men and women -- bred for intelligence and obedience -- embark on an expedition to colonize a distant planet. When they uncover disturbing secrets about the mission, they defy their training and begin to explore their most primitive natures. As life on the ship descends into chaos, they soon become consumed by fear, lust and an insatiable hunger for power.",
      release_date: "2021-04-08",
      title: "Voyagers",
      adult: false,
      backdrop_path: "/9dBSwftCzkC4K4zgMZTwcm58VUR.jpg",
      genre_ids: [878, 10749, 53],
      vote_count: 45,
      original_language: "en",
      original_title: "Voyagers",
      poster_path: "/gn2vCmWO7jQBBto9SYuBHYZARaU.jpg",
      id: 597890,
      popularity: 101.346,
      media_type: "movie",
    },
    {
      original_title: "劇場版「鬼滅の刃」無限列車編",
      poster_path: "/yF45egpHwaYLn4jTyZAgk0Cmug9.jpg",
      video: false,
      vote_average: 8.3,
      overview:
        "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      release_date: "2020-10-16",
      id: 635302,
      adult: false,
      backdrop_path: "/3FVe3OAdgz060JaxIAaUl5lo6cx.jpg",
      vote_count: 805,
      genre_ids: [16, 28, 12, 14, 18],
      title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
      original_language: "ja",
      popularity: 1907.389,
      media_type: "movie",
    },
    {
      vote_average: 8.2,
      overview:
        "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
      release_date: "2021-03-24",
      adult: false,
      backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
      vote_count: 5237,
      genre_ids: [878, 28, 18],
      id: 399566,
      original_language: "en",
      original_title: "Godzilla vs. Kong",
      poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
      title: "Godzilla vs. Kong",
      video: false,
      popularity: 2704.261,
      media_type: "movie",
    },
    {
      original_language: "en",
      original_title: "Tom \u0026 Jerry",
      poster_path: "/yMoMlJo2msoVwmuf6k1C78MrB3H.jpg",
      video: false,
      vote_average: 7.3,
      id: 587807,
      release_date: "2021-02-11",
      vote_count: 1288,
      title: "Tom \u0026 Jerry",
      adult: false,
      backdrop_path: "/9ns9463dwOeo1CK1JU2wirL5Yi1.jpg",
      overview:
        "Tom the cat and Jerry the mouse get kicked out of their home and relocate to a fancy New York hotel, where a scrappy employee named Kayla will lose her job if she can’t evict Jerry before a high-class wedding at the hotel. Her solution? Hiring Tom to get rid of the pesky mouse.",
      genre_ids: [35, 10751, 16],
      popularity: 770.491,
      media_type: "movie",
    },
    {
      origin_country: ["US"],
      overview:
        "As Mexican-American Tejano singer Selena comes of age and realizes her dreams, she and her family make tough choices to hold on to love and music.",
      vote_count: 1211,
      backdrop_path: "/Wu8kh7oyvaIfkNyMJyJHCamh5L.jpg",
      vote_average: 7.5,
      genre_ids: [18],
      name: "Selena: The Series",
      id: 97180,
      first_air_date: "2020-12-04",
      poster_path: "/mYsWyfiIMxx4HDm0Wck7oJ9ckez.jpg",
      original_language: "en",
      original_name: "Selena: The Series",
      popularity: 176.933,
      media_type: "tv",
    },
    {
      title: "Nomadland",
      adult: false,
      backdrop_path: "/bjjZXrP8PEdFeJkKERc62xlarMI.jpg",
      id: 581734,
      original_language: "en",
      original_title: "Nomadland",
      poster_path: "/66GUmWpTHgAjyp4aBSXy63PZTiC.jpg",
      video: false,
      vote_average: 7.4,
      vote_count: 842,
      overview:
        "A woman in her sixties embarks on a journey through the western United States after losing everything in the Great Recession, living as a van-dwelling modern-day nomad.",
      release_date: "2021-01-29",
      genre_ids: [18, 37],
      popularity: 241.047,
      media_type: "movie",
    },
    {
      vote_average: 7.9,
      overview:
        "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
      first_air_date: "2021-03-19",
      vote_count: 5237,
      backdrop_path: "/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg",
      original_name: "The Falcon and the Winter Soldier",
      genre_ids: [10765, 10759, 18, 10768],
      id: 88396,
      original_language: "en",
      origin_country: ["US"],
      poster_path: "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
      name: "The Falcon and the Winter Soldier",
      popularity: 2204.916,
      media_type: "tv",
    },
    {
      overview:
        "While speeding off to help in an impromptu battle, The Flash blazes and rips through time, only to find himself dropped into the middle of World War II. It’s here that The Flash meets Wonder Woman and her top secret team, known as the Justice Society of America. Amidst the raging tides of war, gripping combat and the velocity of valor, The Flash must fight to return to his own timeline.",
      release_date: "2021-04-27",
      title: "Justice Society: World War II",
      id: 736069,
      adult: false,
      backdrop_path: "/8LHSDyRizQ4kQz5rEHPKyXPvMG3.jpg",
      genre_ids: [16, 10752, 878],
      original_language: "en",
      original_title: "Justice Society: World War II",
      poster_path: "/e4REOC6CZW8J6FslA4nRvdQXFXR.jpg",
      vote_count: 135,
      video: false,
      vote_average: 8.3,
      popularity: 740.062,
      media_type: "movie",
    },
    {
      vote_average: 6.9,
      overview:
        "A lonesome stranger with nerves of steel must track down and kill a rogue hitman to satisfy an outstanding debt. But the only information he's been given is a time and location where to find his quarry. No name. No description. Nothing.",
      release_date: "2021-04-30",
      adult: false,
      backdrop_path: "/3Ef8PWUiP1ehO1ESEroxb736srR.jpg",
      vote_count: 17,
      genre_ids: [53, 28, 80],
      id: 808023,
      original_language: "en",
      original_title: "The Virtuoso",
      poster_path: "/vXHzO26mJaOt4VO7ZFiM6No5ScT.jpg",
      title: "The Virtuoso",
      video: false,
      popularity: 151.623,
      media_type: "movie",
    },
    {
      backdrop_path: "/gB9l7epUG4lZKe68bTdL6u6eZCK.jpg",
      genre_ids: [80, 9648, 18],
      original_name: "El inocente",
      original_language: "es",
      poster_path: "/t9BbrpteZ9VxO912WzFRVMTV3z3.jpg",
      vote_count: 8,
      id: 119988,
      vote_average: 9.1,
      name: "The Innocent",
      overview:
        "An accidental killing leads a man down a dark hole of intrigue and murder. Just as he finds love and freedom, one phone call brings back the nightmare.",
      first_air_date: "2021-04-30",
      origin_country: ["ES"],
      popularity: 182.728,
      media_type: "tv",
    },
    {
      poster_path: "/mrVoyDFiDSqfH4mkoRtccOv2vwh.jpg",
      vote_average: 8.4,
      overview:
        "In a world cleaved in two by a massive barrier of perpetual darkness, a young soldier uncovers a power that might finally unite her country. But as she struggles to hone her power, dangerous forces plot against her. Thugs, thieves, assassins and saints are at war now, and it will take more than magic to survive.",
      first_air_date: "2021-04-23",
      id: 85720,
      vote_count: 261,
      original_name: "Shadow and Bone",
      origin_country: ["US"],
      genre_ids: [10765],
      name: "Shadow and Bone",
      original_language: "en",
      backdrop_path: "/8z9qQkx7wA6FXpLV8Tiw9mfsRFK.jpg",
      popularity: 212.341,
      media_type: "tv",
    },
    {
      video: false,
      vote_average: 5.7,
      overview:
        "A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.",
      release_date: "2021-01-01",
      title: "Shadow in the Cloud",
      adult: false,
      backdrop_path: "/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg",
      genre_ids: [27, 28, 18, 10752],
      vote_count: 310,
      original_language: "en",
      original_title: "Shadow in the Cloud",
      poster_path: "/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg",
      id: 675327,
      popularity: 184.148,
      media_type: "movie",
    },
    {
      vote_average: 7.2,
      first_air_date: "2016-01-21",
      overview:
        "When heroes alone are not enough ... the world needs legends. Having seen the future, one he will desperately try to prevent from happening, time-traveling rogue Rip Hunter is tasked with assembling a disparate group of both heroes and villains to confront an unstoppable threat — one in which not only is the planet at stake, but all of time itself. Can this ragtag team defeat an immortal threat unlike anything they have ever known?",
      original_name: "DC's Legends of Tomorrow",
      origin_country: ["US"],
      backdrop_path: "/4LTWJ7WNiSk5SUWhRkHT279026o.jpg",
      genre_ids: [10759, 18, 10765],
      vote_count: 1569,
      original_language: "en",
      name: "DC's Legends of Tomorrow",
      poster_path: "/uzQpQGISbtxc047IOssFo5AiDwU.jpg",
      id: 62643,
      popularity: 203.446,
      media_type: "tv",
    },
    {
      original_title: "Nobody",
      poster_path: "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
      video: false,
      id: 615457,
      overview:
        'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
      release_date: "2021-03-26",
      title: "Nobody",
      adult: false,
      backdrop_path: "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
      vote_count: 1126,
      genre_ids: [28, 53, 80],
      vote_average: 8.5,
      original_language: "en",
      popularity: 2265.723,
      media_type: "movie",
    },
    {
      origin_country: ["US"],
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      vote_count: 14208,
      backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
      vote_average: 8.4,
      genre_ids: [10765, 18, 10759],
      name: "Game of Thrones",
      id: 1399,
      first_air_date: "2011-04-17",
      poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
      original_language: "en",
      original_name: "Game of Thrones",
      popularity: 618.155,
      media_type: "tv",
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export default data;
